services:
  dwh-ch-1:
    image: clickhouse:26.7.5.10-jammy
    container_name: dwh-ch-1
    restart: unless-stopped
    networks:
      - dwh-net
    ports:
      - '38123:8123'      # HTTP интерфейс
      - '39000:9000'      # Native TCP интерфейс
      # - '39009:9009'    # HTTP интерфейс для репликации
    extra_hosts:
      - 'odin:192.168.1.10'
      - 'loki:192.168.1.15'
    volumes:
      - dwh-ch-1-data:/var/lib/clickhouse
      - dwh-ch-1-logs:/var/log/clickhouse-server
      - ./config:/etc/clickhouse-server
    environment:
      - CLICKHOUSE_USER=${CLICKHOUSE__USER}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE__PASSWORD}
    healthcheck:
      test: ['CMD', 'wget', '--spider', '-q', 'http://localhost:8123/ping']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  dwh-ch-1-data:
    name: dwh-ch-1-data
    external: false
  dwh-ch-1-logs:
    name: dwh-ch-1-logs
    external: false
