name: dwh

include:
  - compose/clickhouse/docker-compose.yaml
  - compose/postgres/docker-compose.yaml
  - compose/minio/docker-compose.yaml
  - compose/redpanda/docker-compose.yaml
  - compose/redis/docker-compose.yaml
  - compose/ollama/docker-compose.yaml

networks:
  dwh-net:
    driver: bridge
    name: dwh-net
