connector.name=clickhouse
connection-url=jdbc:clickhouse://clickhouse:8123/default?socket_timeout=43200000&connect_timeout=43200000
connection-user=core
connection-password=core

unsupported-type-handling=CONVERT_TO_VARCHAR
write.batch-size=1000000
insert.non-transactional-insert.enabled=true
clickhouse.map-string-as-varchar=true