services:
  dwh-pg-1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dwh-pg-1
    restart: unless-stopped
    shm_size: 128mb
    networks:
      - dwh-net
    dns:
      - 192.168.1.10
    ports:
      - '35432:5432'
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}
    command:
      - -c
      - listen_addresses=*
    volumes:
      - dwh-pg-1-data:/var/lib/postgresql
      # - ./config/postgresql.conf:/var/lib/postgresql/postgresql.conf  # использовать именованный volume dwh-pg-1-data
      # - ./config/pg_hba.conf:/var/lib/postgresql/pg_hba.conf          # использовать именованный volume dwh-pg-1-data
      # - ./config/pg_ident.conf:/var/lib/postgresql/pg_ident.conf      # использовать именованный volume dwh-pg-1-data
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${PG_USER}', '-d', '${PG_DATABASE}']
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  dwh-pg-1-data:
    name: dwh-pg-1-data
    external: true
