# /etc/redpanda-connect/resources.yml
cache_resources:
  - label: pg_dtl_d_chr_rss_feeds
    redis:
      url: redis://dwh-rd-1:6379
      default_ttl: 24h

  - label: pg_stg_chr_rss_news
    redis:
      url: redis://dwh-rd-1:6379
      default_ttl: 24h

  - label: pg_dtl_h_chr_rss_news
    redis:
      url: redis://dwh-rd-1:6379
      default_ttl: 24h
